export const copy = {
  en: {
    stacks: [
      {
        id: 'js',
        name: 'JavaScript',
        desc: 'Web, Node, full-stack',
        icon: 'JS',
        chip: 'bg-pastel-sand',
      },
      {
        id: 'ts',
        name: 'TypeScript',
        desc: 'Type safety, modern tooling',
        icon: 'TS',
        chip: 'bg-pastel-mist',
      },
      {
        id: 'py',
        name: 'Python',
        desc: 'Backend, data, scripts',
        icon: 'PY',
        chip: 'bg-pastel-sage',
      },
      {
        id: 'react',
        name: 'React',
        desc: 'Components, hooks, state',
        icon: 'RX',
        chip: 'bg-pastel-lavender',
      },
    ],
    levels: [
      {
        id: 'starter',
        name: 'Beginner',
        tag: 'Just starting out',
        desc: 'Variables, conditionals, loops, arrays. No pressure.',
        intensity: 1,
        fill: 'bg-pastel-sage',
      },
      {
        id: 'junior',
        name: 'Junior',
        tag: 'Built a few projects',
        desc: 'Functions, objects, fetch, async/await. Comfortable reading docs.',
        intensity: 2,
        fill: 'bg-pastel-mist',
      },
      {
        id: 'mid',
        name: 'Intermediate',
        tag: 'Ready to level up',
        desc: 'Patterns, architecture, performance. Tougher code reviews.',
        intensity: 3,
        fill: 'bg-pastel-sand',
      },
      {
        id: 'advanced',
        name: 'Advanced',
        tag: 'Big tech ambitions',
        desc: 'Algorithms, optimal complexity, edge cases. FAANG interview energy.',
        intensity: 4,
        fill: 'bg-pastel-lavender',
      },
    ],
    tracks: [
      {
        id: 'code',
        name: 'Code',
        desc: 'Solve a real problem in the editor, with tests.',
        fill: 'bg-pastel-greige',
      },
      {
        id: 'design',
        name: 'System Design',
        desc: 'Architect systems on a canvas; the AI reviews it.',
        fill: 'bg-pastel-mist',
      },
    ],
    stepMeta: [
      {
        title: 'How do you want to train today?',
        subtitle: 'Code or system design (architecture). Pick your track.',
      },
      {
        title: 'Radical honesty: where are you?',
        subtitle:
          'The more honest you are, the better the AI calibrates the challenge.',
      },
      {
        title: 'Time to think.',
        subtitle:
          "I'll generate a real challenge, with a fictional client. No copy-paste.",
      },
    ],
    stepLabels: ['Track', 'Level', 'Ready'],
    setup: 'Setup',
    backToSite: 'Back to site',
    language: 'Language',
    designNotePre: "System design has no language, so you'll ",
    designNoteBold: 'sketch the system architecture',
    designNotePost: ' (services, data, flow) on a canvas and the AI reviews it.',
    trackLabel: 'Track',
    levelLabel: 'Level',
    designValue: 'System Design',
    codeValue: 'Code',
    genError: "The AI couldn't generate a challenge right now. Try again.",
    connError: "Couldn't reach the AI. Check your connection and try again.",
    back: 'Back',
    next: 'Continue',
    retry: 'Try again',
    generate: 'Generate my challenge',
  },
  pt: {
    stacks: [
      {
        id: 'js',
        name: 'JavaScript',
        desc: 'Web, Node, full-stack',
        icon: 'JS',
        chip: 'bg-pastel-sand',
      },
      {
        id: 'ts',
        name: 'TypeScript',
        desc: 'Type safety, tooling moderno',
        icon: 'TS',
        chip: 'bg-pastel-mist',
      },
      {
        id: 'py',
        name: 'Python',
        desc: 'Backend, dados, scripts',
        icon: 'PY',
        chip: 'bg-pastel-sage',
      },
      {
        id: 'react',
        name: 'React',
        desc: 'Componentes, hooks, estado',
        icon: 'RX',
        chip: 'bg-pastel-lavender',
      },
    ],
    levels: [
      {
        id: 'starter',
        name: 'Iniciante',
        tag: 'Comecei agora',
        desc: 'Variáveis, condicionais, loops, arrays. Sem traumas.',
        intensity: 1,
        fill: 'bg-pastel-sage',
      },
      {
        id: 'junior',
        name: 'Júnior',
        tag: 'Já fiz alguns projetos',
        desc: 'Funções, objetos, fetch, async/await. Confortável com docs.',
        intensity: 2,
        fill: 'bg-pastel-mist',
      },
      {
        id: 'mid',
        name: 'Intermediário',
        tag: 'Quero crescer',
        desc: 'Padrões, arquitetura, performance. Code review mais duro.',
        intensity: 3,
        fill: 'bg-pastel-sand',
      },
      {
        id: 'advanced',
        name: 'Avançado',
        tag: 'Quero nível big tech',
        desc: 'Algoritmos, complexidade ótima, edge cases. Pegada de entrevista FAANG.',
        intensity: 4,
        fill: 'bg-pastel-lavender',
      },
    ],
    tracks: [
      {
        id: 'code',
        name: 'Código',
        desc: 'Resolva um problema real no editor, com testes.',
        fill: 'bg-pastel-greige',
      },
      {
        id: 'design',
        name: 'System Design',
        desc: 'Arquitete sistemas num canvas; a IA analisa.',
        fill: 'bg-pastel-mist',
      },
    ],
    stepMeta: [
      {
        title: 'Como você quer treinar hoje?',
        subtitle: 'Código ou system design (arquitetura). Escolha a trilha.',
      },
      {
        title: 'Honestidade radical: onde você está?',
        subtitle: 'Quanto mais real você for, melhor a IA calibra o desafio.',
      },
      {
        title: 'Hora de pensar.',
        subtitle: 'Vou gerar um desafio real, com cliente fictício. Sem cópia.',
      },
    ],
    stepLabels: ['Trilha', 'Nível', 'Pronto'],
    setup: 'Setup',
    backToSite: 'Voltar ao site',
    language: 'Linguagem',
    designNotePre: 'System design não tem linguagem, então você vai ',
    designNoteBold: 'desenhar a arquitetura do sistema',
    designNotePost: ' (serviços, dados, fluxo) num canvas e a IA analisa.',
    trackLabel: 'Trilha',
    levelLabel: 'Nível',
    designValue: 'System Design',
    codeValue: 'Código',
    genError: 'A IA não conseguiu gerar o desafio agora. Tente de novo.',
    connError: 'Falha ao falar com a IA. Verifique a conexão e tente de novo.',
    back: 'Voltar',
    next: 'Continuar',
    retry: 'Tentar de novo',
    generate: 'Gerar meu desafio',
  },
} as const
