import { HINT_PACK } from '@/features/hints/constants'

export const copy = {
  en: {
    library: 'Library',
    how: 'How it works',
    dashboard: 'Dashboard',
    signIn: 'Sign in',
    cta: 'Start a challenge',
    profile: 'Your profile',
    avatar: 'Your avatar',
    hintsAvailable: 'Available hints: 35 free per week, resets Sunday 23:59',
    hintsResetIn: (d: number) =>
      `Weekly hints · resets in ${d} ${d === 1 ? 'day' : 'days'}`,
    buyHints: `Buy +${HINT_PACK.hints} hints`,
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    hints: 'Hints',
    ranking: 'Ranking',
    yourRank: 'Your position in the ranking',
    train: 'Practice',
    trackCode: 'Code',
    trackCodeDesc: 'A real editor, hidden tests',
    trackCodeQ: 'Can you make the tests pass?',
    trackDesign: 'System Design',
    trackDesignDesc: 'Architecture on canvas, reviewed by vision',
    trackDesignQ: 'Will it survive a million users?',
    resume: 'Pick up where you left off',
    explore: 'Browse the library',
    streakTitle: 'day streak — every 7th day pays bonus hints',
    community: 'Community',
    libraryDesc: 'Every challenge ever generated',
    libraryQ: "Which one can't you solve yet?",
    rankingDesc: 'Who trains with the most independence',
    rankingQ: 'How much do you solve on your own?',
    solutionsTitle: 'Solutions',
    solutionsDesc: 'How others solved what you completed',
    solutionsQ: 'How did others think it through?',
  },
  pt: {
    library: 'Biblioteca',
    how: 'Como funciona',
    dashboard: 'Dashboard',
    signIn: 'Entrar',
    cta: 'Comece um desafio',
    profile: 'Seu perfil',
    avatar: 'Seu avatar',
    hintsAvailable: 'Hints disponíveis: 35 grátis por semana, reseta domingo 23:59',
    hintsResetIn: (d: number) =>
      `Hints da semana · reseta em ${d} ${d === 1 ? 'dia' : 'dias'}`,
    buyHints: `Comprar +${HINT_PACK.hints} hints`,
    openMenu: 'Abrir menu',
    closeMenu: 'Fechar menu',
    hints: 'Hints',
    ranking: 'Ranking',
    yourRank: 'Sua posição no ranking',
    train: 'Treinar',
    trackCode: 'Código',
    trackCodeDesc: 'Editor de verdade, testes escondidos',
    trackCodeQ: 'Consegue fazer os testes passarem?',
    trackDesign: 'System Design',
    trackDesignDesc: 'Arquitetura em canvas, avaliada por visão',
    trackDesignQ: 'Aguenta um milhão de usuários?',
    resume: 'Continue de onde parou',
    explore: 'Explore a biblioteca',
    streakTitle: 'dias seguidos — a cada 7 dias você ganha hints bônus',
    community: 'Comunidade',
    libraryDesc: 'Todos os desafios já gerados',
    libraryQ: 'Qual você ainda não resolve?',
    rankingDesc: 'Quem treina com mais independência',
    rankingQ: 'Quanto você resolve sozinho?',
    solutionsTitle: 'Soluções',
    solutionsDesc: 'Como outros resolveram o que você completou',
    solutionsQ: 'Como outros pensaram o problema?',
  },
} as const
